%% Master_Script_Input: Calls the xls file and transforms it into a matlab array
%  (approximate run time of this scripts: 1 minute)
%  This script calls the proprietary function:
%  xls_to_array


path_root = '../';

url       = strcat(path_root,'3Data/Agency_Data_MPV_LEOKA_OKLE_CENSUS_PLUS.xlsx');

variables = {'ORI9',...
             'NAME',...             
             'REGION',...
             'STATENAME',...
             'COUNTYNAME',...
             'FIPS',...
             'AGCYTYPE',...
             'FPLACE',...
             'YEAR',...
             'HOMICIDES',...
             'OFFICERS',...
             'POPULATION',...
             'CORE_CITY',...
             'OKLE_POP',...
             'MURDERS',...
             'VIOLENT_CRIME',...
             'PROPERTY_CRIME',...
             'GUN_DEATH_RATE',...
             'BLACK_POPULATION',...
             'HISPANIC_POPULATION',...
             'ASSAULTS_TOTAL',...
             'BELOW_POVERTY',...
             'CENSUS_POPULATION',...
             'GARNER',...
             'LEOBR',...
             'LAND_AREA'...
             };

only_police_departments = 1; 

addpath(strcat(path_root,'2functions'))

[LEA_data, ...
 NAMES,...
 ORI9,...
 REGION,...
 STATE,...
 COUNTY,...
 FIPS,...
 FPLACE,...
 AGCYTYPE,...
 fields_names,...
 rowsWithMissing,...
 table_missing] = create_array_file(path_root,...
                                            url,...
                                            variables,...
                                            only_police_departments);
                                        
clear variables                                        
                                        
save(strcat(path_root,'4Output/mat/LEA_data_array.mat'));