function [LEA_data, ...
 NAMES,...
 ORI9,...
 REGION,...
 STATE,...
 COUNTY,...
 FIPS,...
 FPLACE,...
 AGCYTYPE,...
 fields_names,...
 rowsWithMissing,...
 table_missing] = create_array_file(path_root, url,variables, only_pd)
%% create_array_file: This function transforms the xls raw file into a matlab array
%
% Author: José Luis Montiel Olea. Last Revised: May 24th, 2021
%
% Built using MATLAB Version: 9.10.0.1538726 (R2021a) Prerelease
%
% Syntax: [LEA_data, ...
%          NAMES,...
%          ORI9,...
%          REGION,...
%          STATE,...
%          COUNTY,...
%          FIPS,...
%          AGCYTYPE,...
%          fields_names,...
%          rowsWithMissing,...
%          table_missing] = create_array_file(path_root, url,variables, only_pd)
%
% INPUT:
% path_root: path for the main directory with the xls file
% url: name of the xls file including file
% variables: cell with the names of the variables
% only_pd: Set to 1 to extract only police departments

%% 1) Read table and filter out non-PDs
table_LEA = readtable(url,'Sheet','Sheet1');

if only_pd == 1
    
table_LEA = table_LEA(table_LEA.AGCYTYPE==0,:); 
            %Focus only on Police Departments

else            
            
end

clear url

table_LEA = table_LEA(:, variables);

%% 2) Delete observations with missing values

Missing_index   = ismissing(table_LEA);

rowsWithMissing = table_LEA(any(Missing_index,2),:);

table_missing   = table_LEA(any(Missing_index,2),:);

table_LEA       = table_LEA(~any(Missing_index,2),:); 

%% 3) Transform table LEA into a matlab array
% (using the function xls_to_array)

addpath(strcat(path_root,'2functions'));

[LEA_data, ...
 NAMES,...
 ORI9,...
 REGION,...
 STATE,...
 COUNTY,...
 FIPS,...
 FPLACE,...
 AGCYTYPE,...
 fields_names] ...
          = xls_to_array(table_LEA,variables);
      
clear variables table_LEA       

end